const actionTypes = {
    "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
    "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "STALEMATE" : "STALEMATE",
    "NEW_GAME" : "NEW_GAME",
    "INSUFFICIENT_MATERIAL" : "INSUFFICIENT_MATERIAL",
    "WIN" : "WIN",
}

export default actionTypes